/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oop.reguler.SiRental.swing.customer;

import com.oop.reguler.SiRental.pojo.Customer;
import com.oop.reguler.SiRental.pojo.Member;
import com.oop.reguler.SiRental.pojo.Mobil;
import com.oop.reguler.SiRental.pojo.Transaksi;
import com.oop.reguler.SiRental.service.TransaksiService;
import com.oop.reguler.SiRental.serviceimpl.CustomerServiceImpl;
import com.oop.reguler.SiRental.serviceimpl.MobilServiceImpl;
import com.oop.reguler.SiRental.serviceimpl.TransaksiServiceImpl;
import com.oop.reguler.SiRental.swing.landingpage.LandingPageCustomer;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author MEMi
 */
public class CustomerCariMobil extends javax.swing.JFrame {

  MobilServiceImpl mobilServiceImpl;
  private static Customer customer;

  /**
   * Creates new form CustomerCariMobil
   */
  public CustomerCariMobil(Customer customer) {
    initComponents();
    this.setLocationRelativeTo(null);
    this.customer = customer;
    loadData();
    lblNamaCustomer.setText(customer.getNama());
  }

  public void close() {
    WindowEvent we = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
  }

  private void emptyField() {
    txtIdMobil.setText("");
    txtIdMember.setText("");
    txtTglSewa.setText("");
    txtLamaSewa.setText("");
    txtLamaSewaKonfirm.setText("");
    txtPlatNo.setText("");
    txtMerk.setText("");
    txtJenis.setText("");
    txtWarna.setText("");
    txtKapasitas.setText("");
    txtTransmisi.setText("");
    txtTahun.setText("");
    txtHarga.setText("");
    txtPajak.setText("");
    txtHargaDurasi.setText("");
    txtTotalHarga.setText("");
  }

  private void loadData() {
    mobilServiceImpl = new MobilServiceImpl();
    List<Mobil> listMobil;
    listMobil = mobilServiceImpl.findAllMobilCustomer();
    Object[][] objectMobil = new Object[listMobil.size()][10];

    int counter = 0;

    for (Mobil mobil : listMobil) {
      objectMobil[counter][0] = mobil.getIdMobil();
      objectMobil[counter][1] = mobil.getMember().getIdMember();
      objectMobil[counter][2] = mobil.getPlatNo();
      objectMobil[counter][3] = mobil.getMerk();
      objectMobil[counter][4] = mobil.getWarna();
      objectMobil[counter][5] = mobil.getJenis();
      objectMobil[counter][6] = mobil.getKapasitas();
      objectMobil[counter][7] = mobil.getTransmisi();
      objectMobil[counter][8] = mobil.getTahunKeluar();
      objectMobil[counter][9] = mobil.getHarga();
      counter++;
    }
    tblCariMobil.setModel(new javax.swing.table.DefaultTableModel(
            objectMobil, new String[]{
              "ID Mobil", "ID Member", "Plat No", "Merk", "Warna", "Jenis", "Kapasitas", "Transmisi", "Tahun", "Harga"
            }
    ));

    double saldoCustomer = customer.getSaldo();
    txtSaldoCustomer.setText(saldoCustomer + "");
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    navbar = new javax.swing.JPanel();
    SiRental = new javax.swing.JLabel();
    btnHome = new javax.swing.JButton();
    btnCariMobil = new javax.swing.JButton();
    profile = new javax.swing.JLabel();
    lblNamaCustomer = new javax.swing.JLabel();
    btnMobilDisewa = new javax.swing.JButton();
    mainPage = new javax.swing.JPanel();
    jenisMobil = new javax.swing.JLabel();
    txtCariMobil = new javax.swing.JTextField();
    btnCari = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblCariMobil = new javax.swing.JTable();
    chooserTanggalSewa = new com.toedter.calendar.JDateChooser();
    jcSewa = new javax.swing.JLabel();
    lamaSewa = new javax.swing.JLabel();
    txtLamaSewa = new javax.swing.JTextField();
    jPanel1 = new javax.swing.JPanel();
    idMobil = new javax.swing.JLabel();
    tglSewa = new javax.swing.JLabel();
    lamaSewa1 = new javax.swing.JLabel();
    txtIdMobil = new javax.swing.JTextField();
    txtTglSewa = new javax.swing.JTextField();
    txtLamaSewaKonfirm = new javax.swing.JTextField();
    txtPlatNo = new javax.swing.JTextField();
    platNo = new javax.swing.JLabel();
    platNo1 = new javax.swing.JLabel();
    txtMerk = new javax.swing.JTextField();
    jenis = new javax.swing.JLabel();
    txtJenis = new javax.swing.JTextField();
    warna = new javax.swing.JLabel();
    txtWarna = new javax.swing.JTextField();
    kapasitas = new javax.swing.JLabel();
    txtKapasitas = new javax.swing.JTextField();
    transmisi = new javax.swing.JLabel();
    txtTransmisi = new javax.swing.JTextField();
    tahun = new javax.swing.JLabel();
    txtTahun = new javax.swing.JTextField();
    Harga = new javax.swing.JLabel();
    txtHarga = new javax.swing.JTextField();
    pajak = new javax.swing.JLabel();
    txtPajak = new javax.swing.JTextField();
    pajak1 = new javax.swing.JLabel();
    txtHargaDurasi = new javax.swing.JTextField();
    totalHarga = new javax.swing.JLabel();
    txtTotalHarga = new javax.swing.JTextField();
    jSeparator1 = new javax.swing.JSeparator();
    btnSewa = new javax.swing.JButton();
    btnPilihMobil = new javax.swing.JButton();
    txtIdMember = new javax.swing.JTextField();
    idMobil1 = new javax.swing.JLabel();
    btnRefresh = new javax.swing.JButton();
    Nama2 = new javax.swing.JLabel();
    txtSaldoCustomer = new javax.swing.JTextField();
    txtRp = new javax.swing.JTextField();
    jSeparator2 = new javax.swing.JSeparator();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    navbar.setBackground(new java.awt.Color(33, 33, 33));
    navbar.setPreferredSize(new java.awt.Dimension(800, 50));

    SiRental.setFont(new java.awt.Font("Neusharp", 1, 20)); // NOI18N
    SiRental.setForeground(new java.awt.Color(255, 255, 255));
    SiRental.setText("SI RENTAL");

    btnHome.setBackground(new java.awt.Color(33, 33, 33));
    btnHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnHome.setForeground(new java.awt.Color(255, 255, 255));
    btnHome.setText("Home");
    btnHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    btnHome.setBorderPainted(false);
    btnHome.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnHomeActionPerformed(evt);
      }
    });

    btnCariMobil.setBackground(new java.awt.Color(33, 33, 33));
    btnCariMobil.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnCariMobil.setForeground(new java.awt.Color(255, 255, 255));
    btnCariMobil.setText("Cari Mobil");
    btnCariMobil.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    btnCariMobil.setBorderPainted(false);
    btnCariMobil.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCariMobilActionPerformed(evt);
      }
    });

    profile.setIcon(new javax.swing.ImageIcon("C:\\Users\\benna\\OneDrive\\Documents\\Itenas Doc Ben\\PROGRAMING LANGUAGE\\Java\\OOP\\OOPRegulerFinal\\ProjectSiRental\\SiRental\\src\\main\\java\\com\\oop\\reguler\\SiRental\\swing\\resources\\profile-user.png")); // NOI18N
    profile.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        profileMouseClicked(evt);
      }
    });

    lblNamaCustomer.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    lblNamaCustomer.setForeground(new java.awt.Color(255, 255, 255));
    lblNamaCustomer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    lblNamaCustomer.setText("User");

    btnMobilDisewa.setBackground(new java.awt.Color(33, 33, 33));
    btnMobilDisewa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnMobilDisewa.setForeground(new java.awt.Color(255, 255, 255));
    btnMobilDisewa.setText("Mobil Disewa");
    btnMobilDisewa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    btnMobilDisewa.setBorderPainted(false);
    btnMobilDisewa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnMobilDisewaActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
    navbar.setLayout(navbarLayout);
    navbarLayout.setHorizontalGroup(
      navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(navbarLayout.createSequentialGroup()
        .addGap(50, 50, 50)
        .addComponent(SiRental)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)
        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnCariMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnMobilDisewa, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(264, 264, 264)
        .addComponent(lblNamaCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(profile)
        .addGap(50, 50, 50))
    );
    navbarLayout.setVerticalGroup(
      navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(navbarLayout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(SiRental)
          .addComponent(btnHome)
          .addComponent(btnCariMobil)
          .addComponent(profile)
          .addComponent(lblNamaCustomer)
          .addComponent(btnMobilDisewa))
        .addContainerGap(8, Short.MAX_VALUE))
    );

    getContentPane().add(navbar, java.awt.BorderLayout.PAGE_START);

    mainPage.setBackground(new java.awt.Color(255, 0, 70));
    mainPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jenisMobil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jenisMobil.setForeground(new java.awt.Color(255, 255, 255));
    jenisMobil.setText("Cari Mobil");
    mainPage.add(jenisMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 12, -1, -1));

    txtCariMobil.setText("Merk...");
    txtCariMobil.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        txtCariMobilMouseClicked(evt);
      }
    });
    txtCariMobil.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtCariMobilActionPerformed(evt);
      }
    });
    mainPage.add(txtCariMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 38, 200, 35));

    btnCari.setBackground(new java.awt.Color(33, 33, 33));
    btnCari.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnCari.setForeground(new java.awt.Color(255, 255, 255));
    btnCari.setText("Cari");
    btnCari.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCariActionPerformed(evt);
      }
    });
    mainPage.add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 38, 60, 35));

    tblCariMobil.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
      },
      new String [] {
        "ID Mobil", "ID Member", "No Plat", "Merk", "Jenis", "Warna", "Kapasitas", "Transmisi", "Tahun", "Harga"
      }
    ));
    tblCariMobil.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tblCariMobilMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tblCariMobil);

    mainPage.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 690, 340));

    chooserTanggalSewa.setBackground(new java.awt.Color(255, 255, 255));
    chooserTanggalSewa.setForeground(new java.awt.Color(33, 33, 33));
    mainPage.add(chooserTanggalSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 38, 125, 35));

    jcSewa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jcSewa.setForeground(new java.awt.Color(255, 255, 255));
    jcSewa.setText("Pilih Tanggal Pesan");
    mainPage.add(jcSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 12, -1, -1));

    lamaSewa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    lamaSewa.setForeground(new java.awt.Color(255, 255, 255));
    lamaSewa.setText("Lama Sewa");
    mainPage.add(lamaSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 12, -1, -1));

    txtLamaSewa.setForeground(new java.awt.Color(33, 33, 33));
    mainPage.add(txtLamaSewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 38, 70, 35));

    jPanel1.setBackground(new java.awt.Color(68, 68, 68));

    idMobil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    idMobil.setForeground(new java.awt.Color(255, 255, 255));
    idMobil.setText("ID Mobil");

    tglSewa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    tglSewa.setForeground(new java.awt.Color(255, 255, 255));
    tglSewa.setText("Tanggal Pesan");

    lamaSewa1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    lamaSewa1.setForeground(new java.awt.Color(255, 255, 255));
    lamaSewa1.setText("Lama Sewa");

    txtIdMobil.setEditable(false);
    txtIdMobil.setBackground(new java.awt.Color(255, 255, 255));
    txtIdMobil.setForeground(new java.awt.Color(33, 33, 33));
    txtIdMobil.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtIdMobilActionPerformed(evt);
      }
    });

    txtTglSewa.setEditable(false);
    txtTglSewa.setBackground(new java.awt.Color(255, 255, 255));
    txtTglSewa.setForeground(new java.awt.Color(33, 33, 33));

    txtLamaSewaKonfirm.setEditable(false);
    txtLamaSewaKonfirm.setBackground(new java.awt.Color(255, 255, 255));
    txtLamaSewaKonfirm.setForeground(new java.awt.Color(33, 33, 33));

    txtPlatNo.setEditable(false);
    txtPlatNo.setBackground(new java.awt.Color(255, 255, 255));
    txtPlatNo.setForeground(new java.awt.Color(33, 33, 33));

    platNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    platNo.setForeground(new java.awt.Color(255, 255, 255));
    platNo.setText("Plat No");

    platNo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    platNo1.setForeground(new java.awt.Color(255, 255, 255));
    platNo1.setText("Merk");

    txtMerk.setEditable(false);
    txtMerk.setBackground(new java.awt.Color(255, 255, 255));
    txtMerk.setForeground(new java.awt.Color(33, 33, 33));

    jenis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jenis.setForeground(new java.awt.Color(255, 255, 255));
    jenis.setText("Jenis");

    txtJenis.setEditable(false);
    txtJenis.setBackground(new java.awt.Color(255, 255, 255));
    txtJenis.setForeground(new java.awt.Color(33, 33, 33));

    warna.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    warna.setForeground(new java.awt.Color(255, 255, 255));
    warna.setText("Warna");

    txtWarna.setEditable(false);
    txtWarna.setBackground(new java.awt.Color(255, 255, 255));
    txtWarna.setForeground(new java.awt.Color(33, 33, 33));

    kapasitas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    kapasitas.setForeground(new java.awt.Color(255, 255, 255));
    kapasitas.setText("Kapasitas");

    txtKapasitas.setEditable(false);
    txtKapasitas.setBackground(new java.awt.Color(255, 255, 255));
    txtKapasitas.setForeground(new java.awt.Color(33, 33, 33));

    transmisi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    transmisi.setForeground(new java.awt.Color(255, 255, 255));
    transmisi.setText("Transmisi");

    txtTransmisi.setEditable(false);
    txtTransmisi.setBackground(new java.awt.Color(255, 255, 255));
    txtTransmisi.setForeground(new java.awt.Color(33, 33, 33));

    tahun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    tahun.setForeground(new java.awt.Color(255, 255, 255));
    tahun.setText("Tahun");

    txtTahun.setEditable(false);
    txtTahun.setBackground(new java.awt.Color(255, 255, 255));
    txtTahun.setForeground(new java.awt.Color(33, 33, 33));

    Harga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    Harga.setForeground(new java.awt.Color(255, 255, 255));
    Harga.setText("Harga");

    txtHarga.setEditable(false);
    txtHarga.setBackground(new java.awt.Color(255, 255, 255));
    txtHarga.setForeground(new java.awt.Color(33, 33, 33));

    pajak.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    pajak.setForeground(new java.awt.Color(255, 255, 255));
    pajak.setText("Pajak");

    txtPajak.setEditable(false);
    txtPajak.setBackground(new java.awt.Color(255, 255, 255));
    txtPajak.setForeground(new java.awt.Color(33, 33, 33));

    pajak1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    pajak1.setForeground(new java.awt.Color(255, 255, 255));
    pajak1.setText("Harga Durasi");

    txtHargaDurasi.setEditable(false);
    txtHargaDurasi.setBackground(new java.awt.Color(255, 255, 255));
    txtHargaDurasi.setForeground(new java.awt.Color(33, 33, 33));

    totalHarga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    totalHarga.setForeground(new java.awt.Color(255, 255, 255));
    totalHarga.setText("Total Harga");

    txtTotalHarga.setEditable(false);
    txtTotalHarga.setBackground(new java.awt.Color(255, 255, 255));
    txtTotalHarga.setForeground(new java.awt.Color(33, 33, 33));

    jSeparator1.setForeground(new java.awt.Color(255, 0, 70));

    btnSewa.setBackground(new java.awt.Color(255, 0, 70));
    btnSewa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnSewa.setForeground(new java.awt.Color(255, 255, 255));
    btnSewa.setText("SEWA");
    btnSewa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSewaActionPerformed(evt);
      }
    });

    btnPilihMobil.setBackground(new java.awt.Color(33, 33, 33));
    btnPilihMobil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnPilihMobil.setForeground(new java.awt.Color(255, 255, 255));
    btnPilihMobil.setText("PILIH MOBIL");
    btnPilihMobil.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPilihMobilActionPerformed(evt);
      }
    });

    txtIdMember.setEditable(false);
    txtIdMember.setBackground(new java.awt.Color(255, 255, 255));
    txtIdMember.setForeground(new java.awt.Color(33, 33, 33));
    txtIdMember.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtIdMemberActionPerformed(evt);
      }
    });

    idMobil1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    idMobil1.setForeground(new java.awt.Color(255, 255, 255));
    idMobil1.setText("ID Member");

    btnRefresh.setBackground(new java.awt.Color(33, 33, 33));
    btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
    btnRefresh.setText("REFRESH");
    btnRefresh.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRefreshActionPerformed(evt);
      }
    });

    Nama2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    Nama2.setForeground(new java.awt.Color(255, 255, 255));
    Nama2.setText("Saldo Anda");

    txtSaldoCustomer.setEditable(false);
    txtSaldoCustomer.setBackground(new java.awt.Color(255, 255, 255));
    txtSaldoCustomer.setForeground(new java.awt.Color(33, 33, 33));

    txtRp.setEditable(false);
    txtRp.setBackground(new java.awt.Color(255, 255, 255));
    txtRp.setForeground(new java.awt.Color(33, 33, 33));
    txtRp.setText("Rp.");

    jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(17, 17, 17)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(pajak)
              .addComponent(txtPajak, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(txtHargaDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(pajak1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(totalHarga)
              .addComponent(txtTotalHarga)))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(warna)
                  .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(kapasitas)
                  .addComponent(txtKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(transmisi)
                  .addComponent(txtTransmisi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(txtPlatNo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(platNo)
                  .addComponent(tahun)
                  .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(idMobil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(txtIdMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(idMobil1))
                      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtIdMember, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtMerk, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(platNo1))
                      .addGap(18, 18, 18)
                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jenis)
                        .addComponent(txtJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                          .addComponent(Harga)
                          .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(txtHarga))
                      .addGap(18, 18, 18)
                      .addComponent(btnPilihMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(tglSewa)
                      .addComponent(txtTglSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(lamaSewa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(txtLamaSewaKonfirm))
                    .addGap(18, 18, 18)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGap(2, 2, 2))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(3, 3, 3)
            .addComponent(Nama2)
            .addGap(18, 18, 18)
            .addComponent(txtRp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(txtSaldoCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(15, 15, 15))
      .addComponent(jSeparator2)
      .addComponent(jSeparator1)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addGroup(jPanel1Layout.createSequentialGroup()
              .addComponent(idMobil)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(txtIdMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
              .addComponent(idMobil1)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(txtIdMember)))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(tglSewa)
              .addComponent(lamaSewa1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(txtTglSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(txtLamaSewaKonfirm))))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(platNo)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtPlatNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(platNo1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtMerk, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jenis)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(warna)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(kapasitas)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(transmisi)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtTransmisi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addComponent(tahun)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addComponent(Harga)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnPilihMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addGap(18, 18, 18)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(5, 5, 5)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(totalHarga)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(pajak)
              .addComponent(pajak1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtPajak, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(txtHargaDurasi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtSaldoCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(txtRp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Nama2)))
        .addContainerGap(14, Short.MAX_VALUE))
    );

    mainPage.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 520, 450));

    getContentPane().add(mainPage, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
    LandingPageCustomer landingPageCustomer = new LandingPageCustomer(customer);
    landingPageCustomer.setVisible(true);
    close();
  }//GEN-LAST:event_btnHomeActionPerformed

  private void btnCariMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariMobilActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnCariMobilActionPerformed

  private void btnMobilDisewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMobilDisewaActionPerformed
    CustomerMobilDisewa customerMobilDisewa = new CustomerMobilDisewa(customer);
    customerMobilDisewa.setVisible(true);
    close();
  }//GEN-LAST:event_btnMobilDisewaActionPerformed

  private void btnPilihMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihMobilActionPerformed
    Transaksi transaksi = new Transaksi();
    int lamaSewa;
    double harga, pajak, hargaDurasi, totalHarga;
    String tanggalSewa;
    int dateChecker;

    //TODO: Bikin Exception chooserTanggal
    Date date = chooserTanggalSewa.getDate();
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

    if (txtIdMobil.getText().equals("") && txtHarga.getText().equals("")) {
      JOptionPane.showMessageDialog(null, "Pilih terlebih dahulu Data pada Tabel!");
    } else {
      if (!txtLamaSewa.getText().equals("")) {
        tanggalSewa = dateFormat.format(date);
        harga = Double.parseDouble(txtHarga.getText());
        lamaSewa = Integer.parseInt(txtLamaSewa.getText());
        pajak = hitungPajak(harga);
        hargaDurasi = hitungHargaDurasi(harga, lamaSewa);
        totalHarga = hitungTotalHarga(pajak, hargaDurasi);

        txtTglSewa.setText(tanggalSewa);
        txtLamaSewaKonfirm.setText(lamaSewa + "");
        txtPajak.setText(pajak + "");
        txtHargaDurasi.setText(hargaDurasi + "");
        txtTotalHarga.setText(totalHarga + "");
      } else {
        JOptionPane.showMessageDialog(null, "Isi Lama Sewa dan Pilih Tanggal Pesan terlebih dahulu!");
      }
    }
  }//GEN-LAST:event_btnPilihMobilActionPerformed
  private double hitungPajak(double harga) {
    return 0.1 * harga;
  }

  private double hitungHargaDurasi(double harga, int lamaSewa) {
    return harga * lamaSewa;
  }

  private double hitungTotalHarga(double pajak, double hargaDurasi) {
    return pajak + hargaDurasi;
  }


  private void tblCariMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCariMobilMouseClicked
    int idMobil, idMember, kapasitas, tahun;
    String platNo, merk, jenis, warna;
    char transmisi;
    double harga;

    int row = tblCariMobil.getSelectedRow();
    idMobil = Integer.parseInt(tblCariMobil.getValueAt(row, 0).toString());
    idMember = Integer.parseInt(tblCariMobil.getValueAt(row, 1).toString());
    platNo = tblCariMobil.getValueAt(row, 2).toString();
    merk = tblCariMobil.getValueAt(row, 3).toString();
    jenis = tblCariMobil.getValueAt(row, 4).toString();
    warna = tblCariMobil.getValueAt(row, 5).toString();
    kapasitas = Integer.parseInt(tblCariMobil.getValueAt(row, 6).toString());
    transmisi = tblCariMobil.getValueAt(row, 7).toString().charAt(0);
    tahun = Integer.parseInt(tblCariMobil.getValueAt(row, 8).toString());
    harga = Double.parseDouble(tblCariMobil.getValueAt(row, 9).toString());

    txtIdMobil.setText(idMobil + "");
    txtIdMember.setText(idMember + "");
    txtPlatNo.setText(platNo);
    txtMerk.setText(merk);
    txtJenis.setText(jenis);
    txtWarna.setText(warna);
    txtKapasitas.setText(kapasitas + "");
    if (transmisi == 'A') {
      txtTransmisi.setText("Automatic");
    } else {
      txtTransmisi.setText("Manual");
    }
    txtTahun.setText(tahun + "");
    txtHarga.setText(harga + "");
  }//GEN-LAST:event_tblCariMobilMouseClicked

  private void txtCariMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariMobilActionPerformed
    // TODO add your handling code here:

  }//GEN-LAST:event_txtCariMobilActionPerformed

  private void txtCariMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCariMobilMouseClicked
    txtCariMobil.setText("");
  }//GEN-LAST:event_txtCariMobilMouseClicked

  private void txtIdMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMobilActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtIdMobilActionPerformed

  private void btnSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSewaActionPerformed
    TransaksiService transaksiService = new TransaksiServiceImpl();
    TransaksiServiceImpl transaksiServiceImpl = new TransaksiServiceImpl();
    MobilServiceImpl mobilServiceImpl = new MobilServiceImpl();
    CustomerServiceImpl customerServiceImpl = new CustomerServiceImpl();

    Transaksi transaksi = new Transaksi();
    Member member = new Member();
    Mobil mobil = new Mobil();

    int idMobil, idMember, lamaPeminjaman;
    String tanggalPesan;
    double pajak, hargaDurasi, totalHarga;

    if (txtIdMobil.getText().equals("") && txtHarga.getText().equals("")) {
      JOptionPane.showMessageDialog(null, "Pilih terlebih dahulu Data pada Tabel!");
    } else {
      if (!txtLamaSewa.getText().equals("") || !txtTglSewa.getText().equals("")) {
        idMobil = Integer.parseInt(txtIdMobil.getText());
        idMember = Integer.parseInt(txtIdMember.getText());
        tanggalPesan = txtTglSewa.getText();
        lamaPeminjaman = Integer.parseInt(txtLamaSewaKonfirm.getText());
        pajak = Double.parseDouble(txtPajak.getText());
        hargaDurasi = Double.parseDouble(txtHargaDurasi.getText());
        totalHarga = Double.parseDouble(txtTotalHarga.getText());

        mobil.setIdMobil(idMobil);
        member.setIdMember(idMember);

        transaksi.setMobil(mobil);
        transaksi.setMember(member);
        transaksi.setCostumer(customer);
        transaksi.setTanggalPesan(tanggalPesan);
        transaksi.setLamaPeminjaman(lamaPeminjaman);
        transaksi.setPajak(pajak);
        transaksi.setHargaDurasi(hargaDurasi);
        transaksi.setTotalHarga(totalHarga);

        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Anda yakin untuk melakukan Transaksi?", "Warning", dialogButton);

        if (dialogResult == JOptionPane.YES_OPTION) {
          double saldoCustomer;

          transaksiService.create(transaksi);

          saldoCustomer = customer.getSaldo() - transaksi.getTotalHarga();
          customer.setSaldo(saldoCustomer);
          customerServiceImpl.saldoPengurangan(customer);

          transaksiServiceImpl.updateSaldoAdmin(transaksi);

          transaksiServiceImpl.updateSaldoMember(transaksi);

          mobilServiceImpl.updateStatusOff(idMobil);

          JOptionPane.showMessageDialog(null, "Mobil berhasil diSewa!");

          loadData();
          emptyField();
        }
      } else {
        JOptionPane.showMessageDialog(null, "Isi Lama Sewa dan Pilih Tanggal Pesan terlebih dahulu!");
      }
    }
  }//GEN-LAST:event_btnSewaActionPerformed

  private void txtIdMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMemberActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtIdMemberActionPerformed

  private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
    loadData();
    emptyField();
  }//GEN-LAST:event_btnRefreshActionPerformed

  private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
    String merk;

    merk = txtCariMobil.getText();

    if (txtCariMobil.getText().equals("") || txtCariMobil.getText().equals("Merk...")) {
      JOptionPane.showMessageDialog(null, "Masukkan merk yang ingin dicari terlebih dahulu!");
    } else {
      emptyField();
      mobilServiceImpl = new MobilServiceImpl();
      List<Mobil> listMobil;
      listMobil = mobilServiceImpl.findByMerk(merk);
      Object[][] objectMobil = new Object[listMobil.size()][10];

      int counter = 0;

      for (Mobil mobil : listMobil) {
        objectMobil[counter][0] = mobil.getIdMobil();
        objectMobil[counter][1] = mobil.getMember().getIdMember();
        objectMobil[counter][2] = mobil.getPlatNo();
        objectMobil[counter][3] = mobil.getMerk();
        objectMobil[counter][4] = mobil.getWarna();
        objectMobil[counter][5] = mobil.getJenis();
        objectMobil[counter][6] = mobil.getKapasitas();
        objectMobil[counter][7] = mobil.getTransmisi();
        objectMobil[counter][8] = mobil.getTahunKeluar();
        objectMobil[counter][9] = mobil.getHarga();
        counter++;
      }
      tblCariMobil.setModel(new javax.swing.table.DefaultTableModel(
              objectMobil, new String[]{
                "ID Mobil", "ID Member", "Plat No", "Merk", "Warna", "Jenis", "Kapasitas", "Transmisi", "Tahun", "Harga"
              }
      ));
    }
  }//GEN-LAST:event_btnCariActionPerformed

  private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
    ProfileCustomer profileCustomer = new ProfileCustomer(customer);
    profileCustomer.setVisible(true);
    close();
  }//GEN-LAST:event_profileMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(CustomerCariMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(CustomerCariMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(CustomerCariMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(CustomerCariMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new CustomerCariMobil(customer).setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel Harga;
  private javax.swing.JLabel Nama2;
  private javax.swing.JLabel SiRental;
  private javax.swing.JButton btnCari;
  private javax.swing.JButton btnCariMobil;
  private javax.swing.JButton btnHome;
  private javax.swing.JButton btnMobilDisewa;
  private javax.swing.JButton btnPilihMobil;
  private javax.swing.JButton btnRefresh;
  private javax.swing.JButton btnSewa;
  private com.toedter.calendar.JDateChooser chooserTanggalSewa;
  private javax.swing.JLabel idMobil;
  private javax.swing.JLabel idMobil1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JLabel jcSewa;
  private javax.swing.JLabel jenis;
  private javax.swing.JLabel jenisMobil;
  private javax.swing.JLabel kapasitas;
  private javax.swing.JLabel lamaSewa;
  private javax.swing.JLabel lamaSewa1;
  private javax.swing.JLabel lblNamaCustomer;
  private javax.swing.JPanel mainPage;
  private javax.swing.JPanel navbar;
  private javax.swing.JLabel pajak;
  private javax.swing.JLabel pajak1;
  private javax.swing.JLabel platNo;
  private javax.swing.JLabel platNo1;
  private javax.swing.JLabel profile;
  private javax.swing.JLabel tahun;
  private javax.swing.JTable tblCariMobil;
  private javax.swing.JLabel tglSewa;
  private javax.swing.JLabel totalHarga;
  private javax.swing.JLabel transmisi;
  private javax.swing.JTextField txtCariMobil;
  private javax.swing.JTextField txtHarga;
  private javax.swing.JTextField txtHargaDurasi;
  private javax.swing.JTextField txtIdMember;
  private javax.swing.JTextField txtIdMobil;
  private javax.swing.JTextField txtJenis;
  private javax.swing.JTextField txtKapasitas;
  private javax.swing.JTextField txtLamaSewa;
  private javax.swing.JTextField txtLamaSewaKonfirm;
  private javax.swing.JTextField txtMerk;
  private javax.swing.JTextField txtPajak;
  private javax.swing.JTextField txtPlatNo;
  private javax.swing.JTextField txtRp;
  private javax.swing.JTextField txtSaldoCustomer;
  private javax.swing.JTextField txtTahun;
  private javax.swing.JTextField txtTglSewa;
  private javax.swing.JTextField txtTotalHarga;
  private javax.swing.JTextField txtTransmisi;
  private javax.swing.JTextField txtWarna;
  private javax.swing.JLabel warna;
  // End of variables declaration//GEN-END:variables
}
