/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oop.reguler.SiRental.swing.member;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import com.oop.reguler.SiRental.swing.landingpage.landingPageMember;

/**
 *
 * @author MEMi
 */
public class Mobil extends javax.swing.JFrame {

  /**
   * Creates new form Mobil
   */
  public Mobil() {
    initComponents();
    this.setLocationRelativeTo(null);
  }
  
  public void close(){
        WindowEvent we = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    navbar = new javax.swing.JPanel();
    SiRental = new javax.swing.JLabel();
    btnHome = new javax.swing.JButton();
    btnMobil = new javax.swing.JButton();
    profile = new javax.swing.JLabel();
    namaLogin = new javax.swing.JLabel();
    mainPage = new javax.swing.JPanel();
    logo = new javax.swing.JLabel();
    mobilAnda = new javax.swing.JLabel();
    btnDelete = new javax.swing.JButton();
    btnUpdate = new javax.swing.JButton();
    btnTambah = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    form = new javax.swing.JPanel();
    noPlat = new javax.swing.JLabel();
    txtNoPlat = new javax.swing.JTextField();
    Warna = new javax.swing.JLabel();
    txtWarna = new javax.swing.JTextField();
    Kapasitas = new javax.swing.JLabel();
    Tahun = new javax.swing.JLabel();
    txtTahun = new javax.swing.JTextField();
    Merk = new javax.swing.JLabel();
    txtMerk = new javax.swing.JTextField();
    Jenis = new javax.swing.JLabel();
    Transmisi = new javax.swing.JLabel();
    Harga = new javax.swing.JLabel();
    txtHarga = new javax.swing.JTextField();
    cbTransmisi = new javax.swing.JComboBox<>();
    cbKapasitas = new javax.swing.JComboBox<>();
    cbJenis = new javax.swing.JComboBox<>();
    Status = new javax.swing.JLabel();
    cbStatus = new javax.swing.JComboBox<>();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    navbar.setBackground(new java.awt.Color(33, 33, 33));
    navbar.setPreferredSize(new java.awt.Dimension(800, 50));

    SiRental.setFont(new java.awt.Font("Neusharp", 1, 20)); // NOI18N
    SiRental.setForeground(new java.awt.Color(255, 255, 255));
    SiRental.setText("SI RENTAL");

    btnHome.setBackground(new java.awt.Color(33, 33, 33));
    btnHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnHome.setForeground(new java.awt.Color(255, 255, 255));
    btnHome.setText("Home");
    btnHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    btnHome.setBorderPainted(false);
    btnHome.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnHomeActionPerformed(evt);
      }
    });

    btnMobil.setBackground(new java.awt.Color(33, 33, 33));
    btnMobil.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnMobil.setForeground(new java.awt.Color(255, 255, 255));
    btnMobil.setText("Mobil");
    btnMobil.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    btnMobil.setBorderPainted(false);
    btnMobil.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnMobilActionPerformed(evt);
      }
    });

    profile.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\ITENAS\\OOP\\cobaSIRental\\src\\main\\java\\sirental\\Resources\\profile-user.png")); // NOI18N
    profile.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        profileMouseClicked(evt);
      }
    });

    namaLogin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    namaLogin.setForeground(new java.awt.Color(255, 255, 255));
    namaLogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    namaLogin.setText("Member");

    javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
    navbar.setLayout(navbarLayout);
    navbarLayout.setHorizontalGroup(
      navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(navbarLayout.createSequentialGroup()
        .addGap(50, 50, 50)
        .addComponent(SiRental)
        .addGap(65, 65, 65)
        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
        .addComponent(namaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(profile)
        .addGap(50, 50, 50))
    );
    navbarLayout.setVerticalGroup(
      navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(navbarLayout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(SiRental)
          .addComponent(btnHome)
          .addComponent(btnMobil)
          .addComponent(profile)
          .addComponent(namaLogin))
        .addContainerGap(8, Short.MAX_VALUE))
    );

    getContentPane().add(navbar, java.awt.BorderLayout.PAGE_START);

    mainPage.setBackground(new java.awt.Color(255, 0, 70));

    logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\ITENAS\\OOP\\cobaSIRental\\src\\main\\java\\sirental\\Resources\\icon-moil-kiri.png")); // NOI18N

    mobilAnda.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
    mobilAnda.setForeground(new java.awt.Color(255, 255, 255));
    mobilAnda.setText("Mobil Anda");

    btnDelete.setBackground(new java.awt.Color(33, 33, 33));
    btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    btnDelete.setForeground(new java.awt.Color(255, 255, 255));
    btnDelete.setText("DELETE");
    btnDelete.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDeleteActionPerformed(evt);
      }
    });

    btnUpdate.setBackground(new java.awt.Color(33, 33, 33));
    btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
    btnUpdate.setText("UPDATE");
    btnUpdate.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnUpdateActionPerformed(evt);
      }
    });

    btnTambah.setBackground(new java.awt.Color(33, 33, 33));
    btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    btnTambah.setForeground(new java.awt.Color(255, 255, 255));
    btnTambah.setText("TAMBAH");
    btnTambah.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnTambahActionPerformed(evt);
      }
    });

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null}
      },
      new String [] {
        "ID", "No Plat", "Merk", "Warna", "Jenis", "Kapasitas", "Transmisi", "Tahun", "Harga", "Status"
      }
    ));
    jScrollPane1.setViewportView(jTable1);

    form.setBackground(new java.awt.Color(68, 68, 68));

    noPlat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    noPlat.setForeground(new java.awt.Color(255, 255, 255));
    noPlat.setText("No Plat");

    txtNoPlat.setBackground(new java.awt.Color(255, 255, 255));
    txtNoPlat.setForeground(new java.awt.Color(33, 33, 33));

    Warna.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    Warna.setForeground(new java.awt.Color(255, 255, 255));
    Warna.setText("Warna");

    txtWarna.setBackground(new java.awt.Color(255, 255, 255));
    txtWarna.setForeground(new java.awt.Color(33, 33, 33));

    Kapasitas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    Kapasitas.setForeground(new java.awt.Color(255, 255, 255));
    Kapasitas.setText("Kapasitas");

    Tahun.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    Tahun.setForeground(new java.awt.Color(255, 255, 255));
    Tahun.setText("Tahun");

    txtTahun.setBackground(new java.awt.Color(255, 255, 255));
    txtTahun.setForeground(new java.awt.Color(33, 33, 33));

    Merk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    Merk.setForeground(new java.awt.Color(255, 255, 255));
    Merk.setText("Merk");

    txtMerk.setBackground(new java.awt.Color(255, 255, 255));
    txtMerk.setForeground(new java.awt.Color(33, 33, 33));

    Jenis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    Jenis.setForeground(new java.awt.Color(255, 255, 255));
    Jenis.setText("Jenis");

    Transmisi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    Transmisi.setForeground(new java.awt.Color(255, 255, 255));
    Transmisi.setText("Transmisi");

    Harga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    Harga.setForeground(new java.awt.Color(255, 255, 255));
    Harga.setText("Harga");

    txtHarga.setBackground(new java.awt.Color(255, 255, 255));
    txtHarga.setForeground(new java.awt.Color(33, 33, 33));

    cbTransmisi.setBackground(new java.awt.Color(255, 255, 255));
    cbTransmisi.setForeground(new java.awt.Color(33, 33, 33));
    cbTransmisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automatic", "Manual", " " }));

    cbKapasitas.setBackground(new java.awt.Color(255, 255, 255));
    cbKapasitas.setForeground(new java.awt.Color(33, 33, 33));
    cbKapasitas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 orang", "4 orang", "6 orang", "8 orang" }));

    cbJenis.setBackground(new java.awt.Color(255, 255, 255));
    cbJenis.setForeground(new java.awt.Color(33, 33, 33));
    cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedan", "SUV", "MVP" }));

    Status.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    Status.setForeground(new java.awt.Color(255, 255, 255));
    Status.setText("Status");

    cbStatus.setBackground(new java.awt.Color(255, 255, 255));
    cbStatus.setForeground(new java.awt.Color(33, 33, 33));
    cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Non-Aktif" }));

    javax.swing.GroupLayout formLayout = new javax.swing.GroupLayout(form);
    form.setLayout(formLayout);
    formLayout.setHorizontalGroup(
      formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLayout.createSequentialGroup()
        .addContainerGap(26, Short.MAX_VALUE)
        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(Status)
          .addGroup(formLayout.createSequentialGroup()
            .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(txtNoPlat)
              .addComponent(noPlat)
              .addComponent(Warna)
              .addComponent(txtWarna, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
              .addComponent(Kapasitas)
              .addComponent(Tahun)
              .addComponent(txtTahun, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
              .addComponent(cbKapasitas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(cbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(txtMerk, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
              .addComponent(Merk)
              .addComponent(Jenis)
              .addComponent(Transmisi)
              .addComponent(Harga)
              .addComponent(txtHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
              .addComponent(cbTransmisi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(cbJenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        .addGap(25, 25, 25))
    );
    formLayout.setVerticalGroup(
      formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(formLayout.createSequentialGroup()
        .addGap(28, 28, 28)
        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(formLayout.createSequentialGroup()
            .addComponent(noPlat)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtNoPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(14, 14, 14)
            .addComponent(Warna))
          .addGroup(formLayout.createSequentialGroup()
            .addComponent(Merk)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtMerk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(14, 14, 14)
            .addComponent(Jenis)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(formLayout.createSequentialGroup()
            .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(14, 14, 14)
            .addComponent(Kapasitas))
          .addGroup(formLayout.createSequentialGroup()
            .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(Transmisi)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(cbTransmisi, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
          .addComponent(cbKapasitas))
        .addGap(14, 14, 14)
        .addGroup(formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(formLayout.createSequentialGroup()
            .addComponent(Harga)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(formLayout.createSequentialGroup()
            .addComponent(Tahun)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(Status)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(20, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout mainPageLayout = new javax.swing.GroupLayout(mainPage);
    mainPage.setLayout(mainPageLayout);
    mainPageLayout.setHorizontalGroup(
      mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(mainPageLayout.createSequentialGroup()
        .addContainerGap(28, Short.MAX_VALUE)
        .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPageLayout.createSequentialGroup()
            .addGap(76, 76, 76)
            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btnTambah))
          .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(mainPageLayout.createSequentialGroup()
              .addComponent(mobilAnda)
              .addGap(18, 18, 18)
              .addComponent(logo))))
        .addGap(21, 21, 21))
    );
    mainPageLayout.setVerticalGroup(
      mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(mainPageLayout.createSequentialGroup()
        .addGap(16, 16, 16)
        .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(mainPageLayout.createSequentialGroup()
            .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(logo)
              .addGroup(mainPageLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(mobilAnda)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(41, Short.MAX_VALUE))
    );

    getContentPane().add(mainPage, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
    // TODO add your handling code here:
    landingPageMember lpMember = new landingPageMember();
    lpMember.setVisible(true);
    close();
  }//GEN-LAST:event_btnHomeActionPerformed

  private void btnMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMobilActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnMobilActionPerformed

  private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnDeleteActionPerformed

  private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnUpdateActionPerformed

  private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnTambahActionPerformed

  private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
    // TODO add your handling code here:
    ProfileMember profileMember = new ProfileMember();
    profileMember.setVisible(true);
    close();
    
  }//GEN-LAST:event_profileMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Mobil().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel Harga;
  private javax.swing.JLabel Jenis;
  private javax.swing.JLabel Kapasitas;
  private javax.swing.JLabel Merk;
  private javax.swing.JLabel SiRental;
  private javax.swing.JLabel Status;
  private javax.swing.JLabel Tahun;
  private javax.swing.JLabel Transmisi;
  private javax.swing.JLabel Warna;
  private javax.swing.JButton btnDelete;
  private javax.swing.JButton btnHome;
  private javax.swing.JButton btnMobil;
  private javax.swing.JButton btnTambah;
  private javax.swing.JButton btnUpdate;
  private javax.swing.JComboBox<String> cbJenis;
  private javax.swing.JComboBox<String> cbKapasitas;
  private javax.swing.JComboBox<String> cbStatus;
  private javax.swing.JComboBox<String> cbTransmisi;
  private javax.swing.JPanel form;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  private javax.swing.JLabel logo;
  private javax.swing.JPanel mainPage;
  private javax.swing.JLabel mobilAnda;
  private javax.swing.JLabel namaLogin;
  private javax.swing.JPanel navbar;
  private javax.swing.JLabel noPlat;
  private javax.swing.JLabel profile;
  private javax.swing.JTextField txtHarga;
  private javax.swing.JTextField txtMerk;
  private javax.swing.JTextField txtNoPlat;
  private javax.swing.JTextField txtTahun;
  private javax.swing.JTextField txtWarna;
  // End of variables declaration//GEN-END:variables
}
