/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oop.reguler.SiRental.swing.admin;

import com.oop.reguler.SiRental.pojo.Admin;
import com.oop.reguler.SiRental.pojo.Customer;
import com.oop.reguler.SiRental.service.CustomerService;
import com.oop.reguler.SiRental.serviceimpl.CustomerServiceImpl;
import com.oop.reguler.SiRental.swing.landingpage.LandingPage;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author MEMi
 */
public class DataCustomer extends javax.swing.JFrame {

  public static Admin admin;
  CustomerService customerService;
  DataMember dataMember;
  KelolaTransaksi kelolaTransaksi;
  KelolaMobil kelolaMobil;

  /**
   * Creates new form KelolaMember
   */
  public DataCustomer(Admin admin) {
    initComponents();
    setLocationRelativeTo(null);
    this.admin = admin;
    loadData();
  }

  public void close() {
    WindowEvent we = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
  }

  private void emptyField() {
    txtIdCustomer.setText("");
    txtNama.setText("");
    txtJenisKelamin.setText("");
    txtAlamat.setText("");
    txtTelepon.setText("");
  }

  private void loadData() {
    customerService = new CustomerServiceImpl();
    List<Customer> listCustomer;

    listCustomer = customerService.findAll();
    Object[][] objectCustomer = new Object[listCustomer.size()][5];

    int counter = 0;

    for (Customer customer : listCustomer) {
      objectCustomer[counter][0] = customer.getIdCustomer();
      objectCustomer[counter][1] = customer.getNama();
      objectCustomer[counter][2] = customer.getJenisKelamin();
      objectCustomer[counter][3] = customer.getAlamat();
      objectCustomer[counter][4] = customer.getTelepon();
      counter++;
    }

    tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            objectCustomer, new String[]{
              "ID Customer", "Nama", "Jenis Kelamin", "Alamat", "Telepon"
            }
    ));
    
    double saldoAdmin = admin.getSaldo();
    txtSaldoAdmin1.setText(saldoAdmin + "");
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Nama2 = new javax.swing.JLabel();
    txtRp = new javax.swing.JTextField();
    txtSaldoAdmin = new javax.swing.JTextField();
    navbar = new javax.swing.JPanel();
    SiRental = new javax.swing.JLabel();
    profile = new javax.swing.JLabel();
    namaLogin = new javax.swing.JLabel();
    hiraukan = new javax.swing.JLabel();
    mainPage = new javax.swing.JPanel();
    sidePanel = new javax.swing.JPanel();
    btnkelolaMobil = new javax.swing.JButton();
    btnDataMember = new javax.swing.JButton();
    btnDataCustomer = new javax.swing.JButton();
    btnKelolaTransaksi = new javax.swing.JButton();
    txtSaldoAdmin1 = new javax.swing.JTextField();
    txtRp1 = new javax.swing.JTextField();
    Nama3 = new javax.swing.JLabel();
    btnLogout = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblCustomer = new javax.swing.JTable();
    Nama = new javax.swing.JLabel();
    txtNama = new javax.swing.JTextField();
    JenisKelamin = new javax.swing.JLabel();
    Alamat = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    txtAlamat = new javax.swing.JTextArea();
    txtJenisKelamin = new javax.swing.JTextField();
    Telepon = new javax.swing.JLabel();
    txtTelepon = new javax.swing.JTextField();
    txtIdCustomer = new javax.swing.JTextField();
    Nama1 = new javax.swing.JLabel();

    Nama2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    Nama2.setForeground(new java.awt.Color(255, 255, 255));
    Nama2.setText("Saldo");

    txtRp.setEditable(false);
    txtRp.setBackground(new java.awt.Color(255, 255, 255));
    txtRp.setForeground(new java.awt.Color(33, 33, 33));
    txtRp.setText("Rp.");

    txtSaldoAdmin.setEditable(false);
    txtSaldoAdmin.setBackground(new java.awt.Color(255, 255, 255));
    txtSaldoAdmin.setForeground(new java.awt.Color(33, 33, 33));

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    navbar.setBackground(new java.awt.Color(33, 33, 33));
    navbar.setPreferredSize(new java.awt.Dimension(800, 50));

    SiRental.setFont(new java.awt.Font("Neusharp", 1, 20)); // NOI18N
    SiRental.setForeground(new java.awt.Color(255, 255, 255));
    SiRental.setText("SI RENTAL");

    profile.setIcon(new javax.swing.ImageIcon("C:\\Users\\benna\\OneDrive\\Documents\\Itenas Doc Ben\\PROGRAMING LANGUAGE\\Java\\OOP\\OOPRegulerFinal\\ProjectSiRental\\SiRental\\src\\main\\java\\com\\oop\\reguler\\SiRental\\swing\\resources\\profile-user.png")); // NOI18N

    namaLogin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    namaLogin.setForeground(new java.awt.Color(255, 255, 255));
    namaLogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    namaLogin.setText("Admin");

    hiraukan.setForeground(new java.awt.Color(33, 33, 33));
    hiraukan.setText("jLabel1");

    javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
    navbar.setLayout(navbarLayout);
    navbarLayout.setHorizontalGroup(
      navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(navbarLayout.createSequentialGroup()
        .addGap(50, 50, 50)
        .addComponent(SiRental)
        .addGap(283, 283, 283)
        .addComponent(hiraukan)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
        .addComponent(namaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(profile)
        .addGap(50, 50, 50))
    );
    navbarLayout.setVerticalGroup(
      navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(navbarLayout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(SiRental)
          .addComponent(profile)
          .addComponent(namaLogin)
          .addComponent(hiraukan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(8, Short.MAX_VALUE))
    );

    getContentPane().add(navbar, java.awt.BorderLayout.PAGE_START);

    mainPage.setBackground(new java.awt.Color(255, 0, 70));
    mainPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    sidePanel.setBackground(new java.awt.Color(68, 68, 68));
    sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    btnkelolaMobil.setBackground(new java.awt.Color(68, 68, 68));
    btnkelolaMobil.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnkelolaMobil.setForeground(new java.awt.Color(255, 255, 255));
    btnkelolaMobil.setText("Kelola Mobil");
    btnkelolaMobil.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnkelolaMobilActionPerformed(evt);
      }
    });
    sidePanel.add(btnkelolaMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 190, 50));

    btnDataMember.setBackground(new java.awt.Color(68, 68, 68));
    btnDataMember.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnDataMember.setForeground(new java.awt.Color(255, 255, 255));
    btnDataMember.setText("Data Member");
    btnDataMember.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDataMemberActionPerformed(evt);
      }
    });
    sidePanel.add(btnDataMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, 50));

    btnDataCustomer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnDataCustomer.setForeground(new java.awt.Color(33, 33, 33));
    btnDataCustomer.setText("Data Customer");
    sidePanel.add(btnDataCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, 50));

    btnKelolaTransaksi.setBackground(new java.awt.Color(68, 68, 68));
    btnKelolaTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnKelolaTransaksi.setForeground(new java.awt.Color(255, 255, 255));
    btnKelolaTransaksi.setText("Kelola Transaksi");
    btnKelolaTransaksi.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnKelolaTransaksiActionPerformed(evt);
      }
    });
    sidePanel.add(btnKelolaTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 190, 50));

    txtSaldoAdmin1.setEditable(false);
    txtSaldoAdmin1.setBackground(new java.awt.Color(255, 255, 255));
    txtSaldoAdmin1.setForeground(new java.awt.Color(33, 33, 33));
    sidePanel.add(txtSaldoAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 150, 30));

    txtRp1.setEditable(false);
    txtRp1.setBackground(new java.awt.Color(255, 255, 255));
    txtRp1.setForeground(new java.awt.Color(33, 33, 33));
    txtRp1.setText("Rp.");
    sidePanel.add(txtRp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 40, 30));

    Nama3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    Nama3.setForeground(new java.awt.Color(255, 255, 255));
    Nama3.setText("Saldo");
    sidePanel.add(Nama3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

    btnLogout.setBackground(new java.awt.Color(33, 33, 33));
    btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnLogout.setForeground(new java.awt.Color(255, 255, 255));
    btnLogout.setText("LOGOUT");
    btnLogout.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLogoutActionPerformed(evt);
      }
    });
    sidePanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 140, 40));

    mainPage.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 450));

    tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null}
      },
      new String [] {
        "ID Customer", "Nama", "Jenis Kelamin", "Alamat", "Telepon"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tblCustomerMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tblCustomer);

    mainPage.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 490, 190));

    Nama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    Nama.setForeground(new java.awt.Color(255, 255, 255));
    Nama.setText("Nama");
    mainPage.add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

    txtNama.setEditable(false);
    txtNama.setBackground(new java.awt.Color(255, 255, 255));
    txtNama.setForeground(new java.awt.Color(33, 33, 33));
    mainPage.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 210, 30));

    JenisKelamin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    JenisKelamin.setForeground(new java.awt.Color(255, 255, 255));
    JenisKelamin.setText("Jenis Kelamin");
    mainPage.add(JenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

    Alamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    Alamat.setForeground(new java.awt.Color(255, 255, 255));
    Alamat.setText("Alamat");
    mainPage.add(Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));

    txtAlamat.setEditable(false);
    txtAlamat.setBackground(new java.awt.Color(255, 255, 255));
    txtAlamat.setColumns(20);
    txtAlamat.setForeground(new java.awt.Color(33, 33, 33));
    txtAlamat.setRows(5);
    jScrollPane2.setViewportView(txtAlamat);

    mainPage.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 220, 70));

    txtJenisKelamin.setEditable(false);
    txtJenisKelamin.setBackground(new java.awt.Color(255, 255, 255));
    txtJenisKelamin.setForeground(new java.awt.Color(33, 33, 33));
    mainPage.add(txtJenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 210, 30));

    Telepon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    Telepon.setForeground(new java.awt.Color(255, 255, 255));
    Telepon.setText("Telepon");
    mainPage.add(Telepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

    txtTelepon.setEditable(false);
    txtTelepon.setBackground(new java.awt.Color(255, 255, 255));
    txtTelepon.setForeground(new java.awt.Color(33, 33, 33));
    mainPage.add(txtTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 210, 30));

    txtIdCustomer.setEditable(false);
    txtIdCustomer.setBackground(new java.awt.Color(255, 255, 255));
    txtIdCustomer.setForeground(new java.awt.Color(33, 33, 33));
    mainPage.add(txtIdCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 110, 30));

    Nama1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    Nama1.setForeground(new java.awt.Color(255, 255, 255));
    Nama1.setText("ID Customer");
    mainPage.add(Nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, -1, -1));

    getContentPane().add(mainPage, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnDataMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataMemberActionPerformed
    dataMember = new DataMember(admin);
    dataMember.setVisible(true);
    close();
  }//GEN-LAST:event_btnDataMemberActionPerformed

  private void btnKelolaTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaTransaksiActionPerformed
    kelolaTransaksi = new KelolaTransaksi(admin);
    kelolaTransaksi.setVisible(true);
    close();
  }//GEN-LAST:event_btnKelolaTransaksiActionPerformed

  private void btnkelolaMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkelolaMobilActionPerformed
    kelolaMobil = new KelolaMobil(admin);
    kelolaMobil.setVisible(true);
    close();
  }//GEN-LAST:event_btnkelolaMobilActionPerformed

  private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
    String nama, alamat, telepon;
    char charJenisKelamin;
    int idCustomer;

    int row = tblCustomer.getSelectedRow();
    idCustomer = Integer.parseInt(tblCustomer.getValueAt(row, 0).toString());
    nama = tblCustomer.getValueAt(row, 1).toString();
    charJenisKelamin = tblCustomer.getValueAt(row, 2).toString().charAt(0);
    alamat = tblCustomer.getValueAt(row, 3).toString();
    telepon = tblCustomer.getValueAt(row, 4).toString();

    txtIdCustomer.setText(idCustomer + "");
    txtNama.setText(nama);
    txtAlamat.setText(alamat);
    txtTelepon.setText(telepon);
    if (charJenisKelamin == 'L') {
      txtJenisKelamin.setText("Laki-laki");
    } else {
      txtJenisKelamin.setText("Perempuan");
    }
  }//GEN-LAST:event_tblCustomerMouseClicked

  private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
    int dialogButton = JOptionPane.YES_NO_OPTION;

    int dialogResult = JOptionPane.showConfirmDialog(null, "yakin mau Logout nih?", "Warning", dialogButton);
    if (dialogResult == JOptionPane.YES_OPTION) {
      LandingPage landingPage = new LandingPage();
      admin.setLoginStatus(false);
      landingPage.setVisible(true);
      close();
    }
  }//GEN-LAST:event_btnLogoutActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(DataCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(DataCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(DataCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(DataCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new DataCustomer(admin).setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel Alamat;
  private javax.swing.JLabel JenisKelamin;
  private javax.swing.JLabel Nama;
  private javax.swing.JLabel Nama1;
  private javax.swing.JLabel Nama2;
  private javax.swing.JLabel Nama3;
  private javax.swing.JLabel SiRental;
  private javax.swing.JLabel Telepon;
  private javax.swing.JButton btnDataCustomer;
  private javax.swing.JButton btnDataMember;
  private javax.swing.JButton btnKelolaTransaksi;
  private javax.swing.JButton btnLogout;
  private javax.swing.JButton btnkelolaMobil;
  private javax.swing.JLabel hiraukan;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JPanel mainPage;
  private javax.swing.JLabel namaLogin;
  private javax.swing.JPanel navbar;
  private javax.swing.JLabel profile;
  private javax.swing.JPanel sidePanel;
  private javax.swing.JTable tblCustomer;
  private javax.swing.JTextArea txtAlamat;
  private javax.swing.JTextField txtIdCustomer;
  private javax.swing.JTextField txtJenisKelamin;
  private javax.swing.JTextField txtNama;
  private javax.swing.JTextField txtRp;
  private javax.swing.JTextField txtRp1;
  private javax.swing.JTextField txtSaldoAdmin;
  private javax.swing.JTextField txtSaldoAdmin1;
  private javax.swing.JTextField txtTelepon;
  // End of variables declaration//GEN-END:variables
}
