/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oop.reguler.SiRental.swing.admin;

import com.oop.reguler.SiRental.pojo.Admin;
import com.oop.reguler.SiRental.pojo.Transaksi;
import com.oop.reguler.SiRental.service.TransaksiService;
import com.oop.reguler.SiRental.serviceimpl.TransaksiServiceImpl;
import com.oop.reguler.SiRental.swing.landingpage.LandingPage;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author MEMi
 */
public class KelolaTransaksi extends javax.swing.JFrame {

  public static Admin admin;
  TransaksiService transaksiService;
  DataMember dataMember;
  DataCustomer dataCustomer;
  KelolaMobil kelolaMobil;

  /**
   * Creates new form KelolaMember
   */
  public KelolaTransaksi(Admin admin) {
    initComponents();
    setLocationRelativeTo(null);
    this.admin = admin;
    loadData();
  }

  public void close() {
    WindowEvent we = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
  }

  private void emptyField() {
    txtIdTransaksi.setText("");
    txtIdMobil.setText("");
    txtIdMember.setText("");
    txtIdCustomer.setText("");
    txtTglPesan.setText("");
    txtTglKembali.setText("");
    txtLamaPenyewaan.setText("");
    txtPajak.setText("");
    txtHargaDurasi.setText("");
    txtTotalHarga.setText("");
    txtStatus.setText("");
  }

  private void loadData() {
    transaksiService = new TransaksiServiceImpl();
    List<Transaksi> listTransaksi;

    listTransaksi = transaksiService.findAll();
    Object[][] objectTransaksi = new Object[listTransaksi.size()][11];

    int counter = 0;

    for (Transaksi transaksi : listTransaksi) {
      objectTransaksi[counter][0] = transaksi.getIdTransaksi();
      objectTransaksi[counter][1] = transaksi.getMobil().getIdMobil();
      objectTransaksi[counter][2] = transaksi.getMember().getIdMember();
      objectTransaksi[counter][3] = transaksi.getCustomer().getIdCustomer();
      objectTransaksi[counter][4] = transaksi.getTanggalPesan();
      objectTransaksi[counter][5] = transaksi.getTanggalKembali();
      objectTransaksi[counter][6] = transaksi.getLamaPeminjaman();
      objectTransaksi[counter][7] = transaksi.getPajak();
      objectTransaksi[counter][8] = transaksi.getHargaDurasi();
      objectTransaksi[counter][9] = transaksi.getTotalHarga();
      objectTransaksi[counter][10] = transaksi.getStatus();
      counter++;
    }

    tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            objectTransaksi, new String[]{
              "ID Transaksi", "ID Mobil", "ID Member", "ID Customer",
              "Pesan", "Kembali", "Lama", "Pajak", "Harga Durasi", "Total Harga", "Status"
            }
    ));

    double saldoAdmin = admin.getSaldo();
    txtSaldoAdmin.setText(saldoAdmin + "");
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    navbar = new javax.swing.JPanel();
    SiRental = new javax.swing.JLabel();
    profile = new javax.swing.JLabel();
    namaLogin = new javax.swing.JLabel();
    hiraukan = new javax.swing.JLabel();
    mainPage = new javax.swing.JPanel();
    sidePanel = new javax.swing.JPanel();
    btnKelolaMobil = new javax.swing.JButton();
    btnDataMember = new javax.swing.JButton();
    btnDataCustomer = new javax.swing.JButton();
    btnKelolaTransaksi = new javax.swing.JButton();
    txtSaldoAdmin = new javax.swing.JTextField();
    txtRp1 = new javax.swing.JTextField();
    Nama3 = new javax.swing.JLabel();
    btnLogout = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tblTransaksi = new javax.swing.JTable();
    idTransaksi = new javax.swing.JLabel();
    txtIdMember = new javax.swing.JTextField();
    Warna = new javax.swing.JLabel();
    txtTglPesan = new javax.swing.JTextField();
    tglPesan = new javax.swing.JLabel();
    btnDelete = new javax.swing.JButton();
    txtIdTransaksi = new javax.swing.JTextField();
    txtLamaPenyewaan = new javax.swing.JTextField();
    lamaPenyewaan = new javax.swing.JLabel();
    idMobil = new javax.swing.JLabel();
    txtIdMobil = new javax.swing.JTextField();
    Jenis = new javax.swing.JLabel();
    txtIdCustomer = new javax.swing.JTextField();
    tglKembali = new javax.swing.JLabel();
    txtTglKembali = new javax.swing.JTextField();
    Pajak = new javax.swing.JLabel();
    txtPajak = new javax.swing.JTextField();
    txtHargaDurasi = new javax.swing.JTextField();
    hargaDurasi = new javax.swing.JLabel();
    txtTotalHarga = new javax.swing.JTextField();
    totalHarga = new javax.swing.JLabel();
    txtStatus = new javax.swing.JTextField();
    totalHarga1 = new javax.swing.JLabel();
    btnRefresh = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    navbar.setBackground(new java.awt.Color(33, 33, 33));
    navbar.setPreferredSize(new java.awt.Dimension(800, 50));

    SiRental.setFont(new java.awt.Font("Neusharp", 1, 20)); // NOI18N
    SiRental.setForeground(new java.awt.Color(255, 255, 255));
    SiRental.setText("SI RENTAL");

    profile.setIcon(new javax.swing.ImageIcon("C:\\Users\\benna\\OneDrive\\Documents\\Itenas Doc Ben\\PROGRAMING LANGUAGE\\Java\\OOP\\OOPRegulerFinal\\ProjectSiRental\\SiRental\\src\\main\\java\\com\\oop\\reguler\\SiRental\\swing\\resources\\profile-user.png")); // NOI18N

    namaLogin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    namaLogin.setForeground(new java.awt.Color(255, 255, 255));
    namaLogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    namaLogin.setText("Admin");

    hiraukan.setForeground(new java.awt.Color(33, 33, 33));
    hiraukan.setText("jLabel1");

    javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
    navbar.setLayout(navbarLayout);
    navbarLayout.setHorizontalGroup(
      navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(navbarLayout.createSequentialGroup()
        .addGap(50, 50, 50)
        .addComponent(SiRental)
        .addGap(283, 283, 283)
        .addComponent(hiraukan)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
        .addComponent(namaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(profile)
        .addGap(50, 50, 50))
    );
    navbarLayout.setVerticalGroup(
      navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(navbarLayout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(SiRental)
          .addComponent(profile)
          .addComponent(namaLogin)
          .addComponent(hiraukan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(8, Short.MAX_VALUE))
    );

    getContentPane().add(navbar, java.awt.BorderLayout.PAGE_START);

    mainPage.setBackground(new java.awt.Color(255, 0, 70));
    mainPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    sidePanel.setBackground(new java.awt.Color(68, 68, 68));
    sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    btnKelolaMobil.setBackground(new java.awt.Color(68, 68, 68));
    btnKelolaMobil.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnKelolaMobil.setForeground(new java.awt.Color(255, 255, 255));
    btnKelolaMobil.setText("Kelola Mobil");
    btnKelolaMobil.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnKelolaMobilActionPerformed(evt);
      }
    });
    sidePanel.add(btnKelolaMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 190, 50));

    btnDataMember.setBackground(new java.awt.Color(68, 68, 68));
    btnDataMember.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnDataMember.setForeground(new java.awt.Color(255, 255, 255));
    btnDataMember.setText("Data Member");
    btnDataMember.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDataMemberActionPerformed(evt);
      }
    });
    sidePanel.add(btnDataMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, 50));

    btnDataCustomer.setBackground(new java.awt.Color(68, 68, 68));
    btnDataCustomer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnDataCustomer.setForeground(new java.awt.Color(255, 255, 255));
    btnDataCustomer.setText("Data Customer");
    btnDataCustomer.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDataCustomerActionPerformed(evt);
      }
    });
    sidePanel.add(btnDataCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, 50));

    btnKelolaTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnKelolaTransaksi.setForeground(new java.awt.Color(68, 68, 68));
    btnKelolaTransaksi.setText("Kelola Transaksi");
    sidePanel.add(btnKelolaTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 190, 50));

    txtSaldoAdmin.setEditable(false);
    txtSaldoAdmin.setBackground(new java.awt.Color(255, 255, 255));
    txtSaldoAdmin.setForeground(new java.awt.Color(33, 33, 33));
    sidePanel.add(txtSaldoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 150, 30));

    txtRp1.setEditable(false);
    txtRp1.setBackground(new java.awt.Color(255, 255, 255));
    txtRp1.setForeground(new java.awt.Color(33, 33, 33));
    txtRp1.setText("Rp.");
    sidePanel.add(txtRp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 40, 30));

    Nama3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    Nama3.setForeground(new java.awt.Color(255, 255, 255));
    Nama3.setText("Saldo");
    sidePanel.add(Nama3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

    btnLogout.setBackground(new java.awt.Color(33, 33, 33));
    btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    btnLogout.setForeground(new java.awt.Color(255, 255, 255));
    btnLogout.setText("LOGOUT");
    btnLogout.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLogoutActionPerformed(evt);
      }
    });
    sidePanel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 140, 40));

    mainPage.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 450));

    tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null, null, null, null}
      },
      new String [] {
        "ID Transaksi", "ID Mobil", "ID Member", "ID Customer", "Pesan", "Kembali", "Lama", "Pajak", "Harga Durasi", "Total Harga", "Status"
      }
    ));
    tblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tblTransaksiMouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(tblTransaksi);

    mainPage.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 490, 120));

    idTransaksi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    idTransaksi.setForeground(new java.awt.Color(255, 255, 255));
    idTransaksi.setText("ID Transaksi");
    mainPage.add(idTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

    txtIdMember.setEditable(false);
    txtIdMember.setBackground(new java.awt.Color(255, 255, 255));
    txtIdMember.setForeground(new java.awt.Color(33, 33, 33));
    mainPage.add(txtIdMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 110, 30));

    Warna.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    Warna.setForeground(new java.awt.Color(255, 255, 255));
    Warna.setText("ID Member");
    mainPage.add(Warna, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 90, -1));

    txtTglPesan.setEditable(false);
    txtTglPesan.setBackground(new java.awt.Color(255, 255, 255));
    txtTglPesan.setForeground(new java.awt.Color(33, 33, 33));
    mainPage.add(txtTglPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 210, 30));

    tglPesan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    tglPesan.setForeground(new java.awt.Color(255, 255, 255));
    tglPesan.setText("Tanggal Pesan");
    mainPage.add(tglPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

    btnDelete.setBackground(new java.awt.Color(33, 33, 33));
    btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnDelete.setForeground(new java.awt.Color(255, 255, 255));
    btnDelete.setText("DELETE");
    btnDelete.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDeleteActionPerformed(evt);
      }
    });
    mainPage.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, -1, -1));

    txtIdTransaksi.setEditable(false);
    txtIdTransaksi.setBackground(new java.awt.Color(255, 255, 255));
    txtIdTransaksi.setForeground(new java.awt.Color(33, 33, 33));
    mainPage.add(txtIdTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 110, 30));

    txtLamaPenyewaan.setEditable(false);
    txtLamaPenyewaan.setBackground(new java.awt.Color(255, 255, 255));
    txtLamaPenyewaan.setForeground(new java.awt.Color(33, 33, 33));
    mainPage.add(txtLamaPenyewaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 210, 30));

    lamaPenyewaan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    lamaPenyewaan.setForeground(new java.awt.Color(255, 255, 255));
    lamaPenyewaan.setText("Lama Penyewaaan");
    mainPage.add(lamaPenyewaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

    idMobil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    idMobil.setForeground(new java.awt.Color(255, 255, 255));
    idMobil.setText("ID Mobil");
    mainPage.add(idMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 70, -1));

    txtIdMobil.setEditable(false);
    txtIdMobil.setBackground(new java.awt.Color(255, 255, 255));
    txtIdMobil.setForeground(new java.awt.Color(33, 33, 33));
    mainPage.add(txtIdMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 100, 30));

    Jenis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    Jenis.setForeground(new java.awt.Color(255, 255, 255));
    Jenis.setText("ID Customer");
    mainPage.add(Jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

    txtIdCustomer.setEditable(false);
    txtIdCustomer.setBackground(new java.awt.Color(255, 255, 255));
    txtIdCustomer.setForeground(new java.awt.Color(33, 33, 33));
    mainPage.add(txtIdCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 110, 30));

    tglKembali.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    tglKembali.setForeground(new java.awt.Color(255, 255, 255));
    tglKembali.setText("Tanggal Kembali");
    mainPage.add(tglKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

    txtTglKembali.setEditable(false);
    txtTglKembali.setBackground(new java.awt.Color(255, 255, 255));
    txtTglKembali.setForeground(new java.awt.Color(33, 33, 33));
    mainPage.add(txtTglKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 210, 30));

    Pajak.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    Pajak.setForeground(new java.awt.Color(255, 255, 255));
    Pajak.setText("Pajak");
    mainPage.add(Pajak, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, -1));

    txtPajak.setEditable(false);
    txtPajak.setBackground(new java.awt.Color(255, 255, 255));
    txtPajak.setForeground(new java.awt.Color(33, 33, 33));
    mainPage.add(txtPajak, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 210, 30));

    txtHargaDurasi.setEditable(false);
    txtHargaDurasi.setBackground(new java.awt.Color(255, 255, 255));
    txtHargaDurasi.setForeground(new java.awt.Color(33, 33, 33));
    mainPage.add(txtHargaDurasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 210, 30));

    hargaDurasi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    hargaDurasi.setForeground(new java.awt.Color(255, 255, 255));
    hargaDurasi.setText("Harga Durasi");
    mainPage.add(hargaDurasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

    txtTotalHarga.setEditable(false);
    txtTotalHarga.setBackground(new java.awt.Color(255, 255, 255));
    txtTotalHarga.setForeground(new java.awt.Color(33, 33, 33));
    mainPage.add(txtTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 210, 30));

    totalHarga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    totalHarga.setForeground(new java.awt.Color(255, 255, 255));
    totalHarga.setText("Total Harga");
    mainPage.add(totalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));

    txtStatus.setEditable(false);
    txtStatus.setBackground(new java.awt.Color(255, 255, 255));
    txtStatus.setForeground(new java.awt.Color(33, 33, 33));
    txtStatus.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtStatusActionPerformed(evt);
      }
    });
    mainPage.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 210, 30));

    totalHarga1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    totalHarga1.setForeground(new java.awt.Color(255, 255, 255));
    totalHarga1.setText("Status");
    mainPage.add(totalHarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

    btnRefresh.setBackground(new java.awt.Color(33, 33, 33));
    btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
    btnRefresh.setText("REFRESH");
    btnRefresh.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRefreshActionPerformed(evt);
      }
    });
    mainPage.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, -1, -1));

    getContentPane().add(mainPage, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    int id;
    if (txtIdTransaksi.getText().equals("")) {
      JOptionPane.showMessageDialog(null, "Pilih data terlebih dahulu!");
    } else {

      transaksiService = new TransaksiServiceImpl();
      int dialogButton = JOptionPane.YES_NO_OPTION;

      id = Integer.parseInt(txtIdTransaksi.getText());
      int dialogResult = JOptionPane.showConfirmDialog(null, "Anda yakin untuk menghapus?", "Warning", dialogButton);
      if (dialogResult == JOptionPane.YES_OPTION) {
        transaksiService.delete(id);
        loadData();
        emptyField();
      }
    }
  }//GEN-LAST:event_btnDeleteActionPerformed

  private void btnDataMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataMemberActionPerformed
    dataMember = new DataMember(admin);
    dataMember.setVisible(true);
    close();
  }//GEN-LAST:event_btnDataMemberActionPerformed

  private void btnDataCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataCustomerActionPerformed
    dataCustomer = new DataCustomer(admin);
    dataCustomer.setVisible(true);
    close();
  }//GEN-LAST:event_btnDataCustomerActionPerformed

  private void btnKelolaMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaMobilActionPerformed
    kelolaMobil = new KelolaMobil(admin);
    kelolaMobil.setVisible(true);
    close();
  }//GEN-LAST:event_btnKelolaMobilActionPerformed

  private void tblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiMouseClicked
    // TODO add your handling code here:
    int idTransaksi, idMobil, idMember, idCustomer, lamaPenyewaan;
    String tanggalPesan, tanggalKembali, status;
    double pajak, hargaDurasi, totalHarga;

    int row = tblTransaksi.getSelectedRow();
    idTransaksi = Integer.parseInt(tblTransaksi.getValueAt(row, 0).toString());
    idMobil = Integer.parseInt(tblTransaksi.getValueAt(row, 1).toString());
    idMember = Integer.parseInt(tblTransaksi.getValueAt(row, 2).toString());
    idCustomer = Integer.parseInt(tblTransaksi.getValueAt(row, 3).toString());
    tanggalPesan = tblTransaksi.getValueAt(row, 4).toString();
    tanggalKembali = tblTransaksi.getValueAt(row, 5).toString();
    lamaPenyewaan = Integer.parseInt(tblTransaksi.getValueAt(row, 6).toString());
    pajak = Double.parseDouble(tblTransaksi.getValueAt(row, 7).toString());
    hargaDurasi = Double.parseDouble(tblTransaksi.getValueAt(row, 8).toString());
    totalHarga = Double.parseDouble(tblTransaksi.getValueAt(row, 9).toString());
    status = tblTransaksi.getValueAt(row, 10).toString();

    txtIdTransaksi.setText(idTransaksi + "");
    txtIdMobil.setText(idMobil + "");
    txtIdMember.setText(idMember + "");
    txtIdCustomer.setText(idCustomer + "");
    txtTglPesan.setText(tanggalPesan);
    txtTglKembali.setText(tanggalKembali);
    txtLamaPenyewaan.setText(lamaPenyewaan + "");
    txtPajak.setText(pajak + "");
    txtHargaDurasi.setText(hargaDurasi + "");
    txtTotalHarga.setText(totalHarga + "");
    txtStatus.setText(status);
  }//GEN-LAST:event_tblTransaksiMouseClicked

  private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtStatusActionPerformed

  private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
    emptyField();
  }//GEN-LAST:event_btnRefreshActionPerformed

  private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
    int dialogButton = JOptionPane.YES_NO_OPTION;

    int dialogResult = JOptionPane.showConfirmDialog(null, "yakin mau Logout nih?", "Warning", dialogButton);
    if (dialogResult == JOptionPane.YES_OPTION) {
      LandingPage landingPage = new LandingPage();
      admin.setLoginStatus(false);
      landingPage.setVisible(true);
      close();
    }
  }//GEN-LAST:event_btnLogoutActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(KelolaTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(KelolaTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(KelolaTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(KelolaTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new KelolaTransaksi(admin).setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel Jenis;
  private javax.swing.JLabel Nama3;
  private javax.swing.JLabel Pajak;
  private javax.swing.JLabel SiRental;
  private javax.swing.JLabel Warna;
  private javax.swing.JButton btnDataCustomer;
  private javax.swing.JButton btnDataMember;
  private javax.swing.JButton btnDelete;
  private javax.swing.JButton btnKelolaMobil;
  private javax.swing.JButton btnKelolaTransaksi;
  private javax.swing.JButton btnLogout;
  private javax.swing.JButton btnRefresh;
  private javax.swing.JLabel hargaDurasi;
  private javax.swing.JLabel hiraukan;
  private javax.swing.JLabel idMobil;
  private javax.swing.JLabel idTransaksi;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel lamaPenyewaan;
  private javax.swing.JPanel mainPage;
  private javax.swing.JLabel namaLogin;
  private javax.swing.JPanel navbar;
  private javax.swing.JLabel profile;
  private javax.swing.JPanel sidePanel;
  private javax.swing.JTable tblTransaksi;
  private javax.swing.JLabel tglKembali;
  private javax.swing.JLabel tglPesan;
  private javax.swing.JLabel totalHarga;
  private javax.swing.JLabel totalHarga1;
  private javax.swing.JTextField txtHargaDurasi;
  private javax.swing.JTextField txtIdCustomer;
  private javax.swing.JTextField txtIdMember;
  private javax.swing.JTextField txtIdMobil;
  private javax.swing.JTextField txtIdTransaksi;
  private javax.swing.JTextField txtLamaPenyewaan;
  private javax.swing.JTextField txtPajak;
  private javax.swing.JTextField txtRp1;
  private javax.swing.JTextField txtSaldoAdmin;
  private javax.swing.JTextField txtStatus;
  private javax.swing.JTextField txtTglKembali;
  private javax.swing.JTextField txtTglPesan;
  private javax.swing.JTextField txtTotalHarga;
  // End of variables declaration//GEN-END:variables
}
