/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oop.reguler.SiRental.swing.landingpage;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JLabel;
import com.oop.reguler.SiRental.swing.login.loginMain;
import com.oop.reguler.SiRental.swing.register.registerMain;

/**
 *
 * @author MEMi
 */
public class landingPage extends javax.swing.JFrame {

  /**
   * Creates new form test
   */
  public landingPage() {
    initComponents();
    this.setLocationRelativeTo(null);
  }
  
  public void close(){
        WindowEvent we = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
    }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    navbar = new javax.swing.JPanel();
    SiRental = new javax.swing.JLabel();
    btnLogin = new javax.swing.JButton();
    btnRegister = new javax.swing.JButton();
    mainPage = new javax.swing.JPanel();
    logo = new javax.swing.JLabel();
    kenapaSiRental = new javax.swing.JLabel();
    garis = new javax.swing.JSeparator();
    baris1 = new javax.swing.JLabel();
    baris2 = new javax.swing.JLabel();
    baris3 = new javax.swing.JLabel();
    baris4 = new javax.swing.JLabel();
    btnsewa2 = new javax.swing.JButton();
    instagram = new javax.swing.JLabel();
    facebook = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    navbar.setBackground(new java.awt.Color(33, 33, 33));
    navbar.setPreferredSize(new java.awt.Dimension(800, 50));

    SiRental.setFont(new java.awt.Font("Neusharp", 1, 20)); // NOI18N
    SiRental.setForeground(new java.awt.Color(255, 255, 255));
    SiRental.setText("SI RENTAL");

    btnLogin.setBackground(new java.awt.Color(33, 33, 33));
    btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnLogin.setForeground(new java.awt.Color(255, 255, 255));
    btnLogin.setText("Login");
    btnLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    btnLogin.setBorderPainted(false);
    btnLogin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLoginActionPerformed(evt);
      }
    });

    btnRegister.setBackground(new java.awt.Color(204, 0, 0));
    btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnRegister.setForeground(new java.awt.Color(255, 255, 255));
    btnRegister.setText("Register");
    btnRegister.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    btnRegister.setBorderPainted(false);
    btnRegister.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRegisterActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
    navbar.setLayout(navbarLayout);
    navbarLayout.setHorizontalGroup(
      navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(navbarLayout.createSequentialGroup()
        .addGap(50, 50, 50)
        .addComponent(SiRental)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 418, Short.MAX_VALUE)
        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(50, 50, 50))
    );
    navbarLayout.setVerticalGroup(
      navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(navbarLayout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(SiRental)
          .addComponent(btnLogin)
          .addComponent(btnRegister))
        .addContainerGap(9, Short.MAX_VALUE))
    );

    getContentPane().add(navbar, java.awt.BorderLayout.PAGE_START);

    mainPage.setBackground(new java.awt.Color(255, 0, 70));

    logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\ITENAS\\OOP\\cobaSIRental\\src\\main\\java\\sirental\\Resources\\sirental.jpeg")); // NOI18N

    kenapaSiRental.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
    kenapaSiRental.setForeground(new java.awt.Color(255, 255, 255));
    kenapaSiRental.setText("KENAPA SI RENTAL ?");

    baris1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    baris1.setForeground(new java.awt.Color(255, 255, 255));
    baris1.setText("Nikmati kemudahan  rental mobil dengan");

    baris2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    baris2.setForeground(new java.awt.Color(255, 255, 255));
    baris2.setText("banyak pilihan sewa mobil murah dengan");

    baris3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    baris3.setForeground(new java.awt.Color(255, 255, 255));
    baris3.setText("kualitas yang  siap  memenuhi  kebutuhan ");

    baris4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
    baris4.setForeground(new java.awt.Color(255, 255, 255));
    baris4.setText("berkendara anda");

    btnsewa2.setBackground(new java.awt.Color(255, 255, 255));
    btnsewa2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    btnsewa2.setForeground(new java.awt.Color(0, 0, 0));
    btnsewa2.setText("Daftar Sekarang");
    btnsewa2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnsewa2ActionPerformed(evt);
      }
    });

    instagram.setForeground(new java.awt.Color(255, 255, 255));
    instagram.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\ITENAS\\OOP\\cobaSIRental\\src\\main\\java\\sirental\\Resources\\instagram.png")); // NOI18N
    instagram.setText("SIRental");

    facebook.setForeground(new java.awt.Color(255, 255, 255));
    facebook.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\ITENAS\\OOP\\cobaSIRental\\src\\main\\java\\sirental\\Resources\\facebook.png")); // NOI18N
    facebook.setText("SI_Rental");

    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\ITENAS\\OOP\\cobaSIRental\\src\\main\\java\\sirental\\Resources\\email.png")); // NOI18N
    jLabel2.setText("sirental205@gmail.com");

    javax.swing.GroupLayout mainPageLayout = new javax.swing.GroupLayout(mainPage);
    mainPage.setLayout(mainPageLayout);
    mainPageLayout.setHorizontalGroup(
      mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPageLayout.createSequentialGroup()
        .addGap(50, 50, 50)
        .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(baris1)
          .addComponent(baris2)
          .addComponent(baris3)
          .addComponent(baris4)
          .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addComponent(garis, javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kenapaSiRental, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addComponent(btnsewa2)
          .addGroup(mainPageLayout.createSequentialGroup()
            .addComponent(instagram)
            .addGap(18, 18, 18)
            .addComponent(facebook)
            .addGap(18, 18, 18)
            .addComponent(jLabel2)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
        .addComponent(logo))
    );
    mainPageLayout.setVerticalGroup(
      mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(mainPageLayout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addComponent(logo)
        .addContainerGap(17, Short.MAX_VALUE))
      .addGroup(mainPageLayout.createSequentialGroup()
        .addGap(50, 50, 50)
        .addComponent(kenapaSiRental)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(garis, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(5, 5, 5)
        .addComponent(baris1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(baris2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(baris3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(baris4)
        .addGap(32, 32, 32)
        .addComponent(btnsewa2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(mainPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(instagram)
          .addComponent(facebook)
          .addComponent(jLabel2))
        .addGap(25, 25, 25))
    );

    getContentPane().add(mainPage, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    // TODO add your handling code here:
    loginMain login = new loginMain();
    login.setVisible(true);
    close();
  }//GEN-LAST:event_btnLoginActionPerformed

  private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
    // TODO add your handling code here:
    registerMain regis = new registerMain();
    regis.setVisible(true);
    close();
  }//GEN-LAST:event_btnRegisterActionPerformed

  private void btnsewa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsewa2ActionPerformed
    // TODO add your handling code here:
    registerMain regis = new registerMain();
    regis.setVisible(true);
    close();
  }//GEN-LAST:event_btnsewa2ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(landingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(landingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(landingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(landingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new landingPage().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel SiRental;
  private javax.swing.JLabel baris1;
  private javax.swing.JLabel baris2;
  private javax.swing.JLabel baris3;
  private javax.swing.JLabel baris4;
  private javax.swing.JButton btnLogin;
  private javax.swing.JButton btnRegister;
  private javax.swing.JButton btnsewa2;
  private javax.swing.JLabel facebook;
  private javax.swing.JSeparator garis;
  private javax.swing.JLabel instagram;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel kenapaSiRental;
  private javax.swing.JLabel logo;
  private javax.swing.JPanel mainPage;
  private javax.swing.JPanel navbar;
  // End of variables declaration//GEN-END:variables
}
